

services:
  neo4j:
    image: neo4j:5.12.0
    container_name: tfm_neo4j
    ports:
      - "7474:7474" # HTTP port (Neo4j Browser)
      - "7687:7687" # Bolt port (For Golang backend driver)
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      # Enable APOC plugin which is very useful for attack paths (shortestPath, etc.)
      - NEO4J_PLUGINS=["apoc"]
      # Ajustes de memoria y transacciones (evita TransactionMemoryLimitExceeded / OutOfMemory)
      - NEO4J_db_memory_transaction_max=0
      - NEO4J_dbms_memory_transaction_total_max=0
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_server_memory_pagecache_size=1G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
